<?php

namespace Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class OrderItems extends \OrderItems implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setQuantityOrdered($quantityOrdered)
    {
        $this->__load();
        return parent::setQuantityOrdered($quantityOrdered);
    }

    public function getQuantityOrdered()
    {
        $this->__load();
        return parent::getQuantityOrdered();
    }

    public function setQuantityReceived($quantityReceived)
    {
        $this->__load();
        return parent::setQuantityReceived($quantityReceived);
    }

    public function getQuantityReceived()
    {
        $this->__load();
        return parent::getQuantityReceived();
    }

    public function setCurrentCost($currentCost)
    {
        $this->__load();
        return parent::setCurrentCost($currentCost);
    }

    public function getCurrentCost()
    {
        $this->__load();
        return parent::getCurrentCost();
    }

    public function setPrice($price)
    {
        $this->__load();
        return parent::setPrice($price);
    }

    public function getPrice()
    {
        $this->__load();
        return parent::getPrice();
    }

    public function setOrder(\Orders $order)
    {
        $this->__load();
        return parent::setOrder($order);
    }

    public function getOrder()
    {
        $this->__load();
        return parent::getOrder();
    }

    public function setInventory(\Inventory $inventory)
    {
        $this->__load();
        return parent::setInventory($inventory);
    }

    public function getInventory()
    {
        $this->__load();
        return parent::getInventory();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'quantityOrdered', 'quantityReceived', 'currentCost', 'price', 'order', 'inventory');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}